config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/*
  get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker
  get "manifest" => "rails/pwa#manifest", as: :pwa_manifest

  # Defines the root path route ("/")
  root "home#index"

  get "zipcode" => "home#search"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Only allow modern browsers supporting webp images, web push, badges, import maps, CSS nesting, and CSS :has.
  allow_browser versions: :modern
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @zipcode_req = params[:zipcode] || "94040"
    fetchData(@zipcode_req)
  end

  def search
    @zipcode_req = params[:zipcode]

    if @zipcode_req == ""
      redirect_to action: "index"
    else
      redirect_to action: "index", zipcode: @zipcode_req
    end
  end

  private
    def fetchData(zipcode)
      require "net/http"
      require "json"

      # 94040
      url = URI("https://#{Rails.application.credentials.api[:host]}/api/weather/air_pollution?zip=#{zipcode}%2CUS&type=current")

      http = Net::HTTP.new(url.host, url.port)
      http.use_ssl = true

      request = Net::HTTP::Get.new(url)
      request["x-rapidapi-key"] = Rails.application.credentials.api[:key]
      request["x-rapidapi-host"] = Rails.application.credentials.api[:host]
      request["Accept"] = "application/json"

      response = http.request(request)
      if response.kind_of? Net::HTTPSuccess
        parse = JSON.parse(response.read_body)
        @result = parse["list"][0]["main"]["aqi"]
        if @result <= 50
          @background = "green"
        @description = "Good (0 - 50)"
        elsif @result <= 100
          @background = "yellow"
        @description = "Moderate (51 - 100)"
        elsif @result <= 150
          @background = "orange"
        @description = "Unhealthy for Sensitive Groups (USG) (101 - 150)"
        elsif @result <= 200
          @background = "red"
        @description = "Unhealthy (151 - 200)"
        elsif @result <= 300
          @background = "purple"
        @description = "Very Unhealthy (201 - 300)"
        else
          @background = "maroon"
        @description = "Hazardous (301+)"
        end
      else
        @result = "No data found"
        @background = "bg-light"
        @description = "data error"
      end
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/index.html.erb
<div class="p-5 mb-4 <%= @background %> rounded-3">
  <div class="container-fluid py-5">
    <h1 class="display-5 fw-bold"><%= @result %></h1>
    <p class="col-md-8 fs-4">This is current pollution condition</p>
    <hr class="my-4"/>
    <p><%= @description %></p>
  </div>
</div>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <div class="container-fluid">
    <%= link_to "Weather", root_path, class: "navbar-brand" %>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
      </ul>
      <%= form_tag zipcode_path, :method => 'GET' do %>
        <div class="d-flex">
          <%= text_field_tag 'zipcode', nil, placeholder: "Search Zipcode", class: "form-control me-2", type: "search", 'aria-label':'Search' %>
          <%= submit_tag 'Search', class: "btn btn-outline-secondary" %>
        </div>
      <% end %>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for(:title) || "Weather Rails" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>

    <link rel="manifest" href="/manifest.json">
    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= render 'layouts/navbar' %>
    <div class="container">
    <br/>
    <%= yield %>
    </div>
  </body>
</html>